#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Apr 11, 2019 05:18:34 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import register_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    register_support.set_Tk_var()
    top = Toplevel1 (root)
    register_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    register_support.set_Tk_var()
    top = Toplevel1 (w)
    register_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family {Segoe UI} -size 9"

        top.geometry("404x291+585+210")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")
        top.bind('<Key-Return>',self.run)

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.396, rely=0.825, height=24, width=87)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=self.run)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Register''')

        self.entry_username = tk.Entry(top)
        self.entry_username.place(relx=0.223, rely=0.137, height=20
                , relwidth=0.629)
        self.entry_username.configure(background="white")
        self.entry_username.configure(disabledforeground="#a3a3a3")
        self.entry_username.configure(font="-family {Courier New} -size 10")
        self.entry_username.configure(foreground="#000000")
        self.entry_username.configure(highlightbackground="#d9d9d9")
        self.entry_username.configure(highlightcolor="black")
        self.entry_username.configure(insertbackground="black")
        self.entry_username.configure(selectbackground="#c4c4c4")
        self.entry_username.configure(selectforeground="black")
        self.entry_username.configure(textvariable=register_support.entity_username)

        self.menubar = tk.Menu(top, font=('Segoe UI', 9, ), bg=_bgcolor
                ,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Spinbox_question = tk.Spinbox(top, from_=1.0, to=100.0)
        self.Spinbox_question.place(relx=0.223, rely=0.481, relheight=0.065
                , relwidth=0.631)
        self.Spinbox_question.configure(activebackground="#f9f9f9")
        self.Spinbox_question.configure(background="white")
        self.Spinbox_question.configure(buttonbackground="#d9d9d9")
        self.Spinbox_question.configure(disabledforeground="#a3a3a3")
        self.Spinbox_question.configure(font="-family {Segoe UI} -size 9")
        self.Spinbox_question.configure(foreground="black")
        self.Spinbox_question.configure(highlightbackground="black")
        self.Spinbox_question.configure(highlightcolor="black")
        self.Spinbox_question.configure(insertbackground="black")
        self.Spinbox_question.configure(selectbackground="#c4c4c4")
        self.Spinbox_question.configure(selectforeground="black")
        self.Spinbox_question.configure(textvariable=register_support.spinbox_question)
        self.value_list = [1,2,6,79,]
        self.Spinbox_question.configure(values=self.value_list)

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.025, rely=0.137, height=21, width=74)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Username''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.025, rely=0.275, height=21, width=74)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Password''')

        self.entry_password = tk.Entry(top)
        self.entry_password.place(relx=0.223, rely=0.275, height=20
                , relwidth=0.629)
        self.entry_password.configure(background="white")
        self.entry_password.configure(disabledforeground="#a3a3a3")
        self.entry_password.configure(font="-family {Courier New} -size 10")
        self.entry_password.configure(foreground="#000000")
        self.entry_password.configure(highlightbackground="#d9d9d9")
        self.entry_password.configure(highlightcolor="black")
        self.entry_password.configure(insertbackground="black")
        self.entry_password.configure(selectbackground="#c4c4c4")
        self.entry_password.configure(selectforeground="black")
        self.entry_password.configure(textvariable=register_support.entitiy_password)

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.025, rely=0.481, height=21, width=74)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Quiestion''')

        self.entry_aswer = tk.Entry(top)
        self.entry_aswer.place(relx=0.223, rely=0.619, height=20, relwidth=0.629)

        self.entry_aswer.configure(background="white")
        self.entry_aswer.configure(disabledforeground="#a3a3a3")
        self.entry_aswer.configure(font="-family {Courier New} -size 10")
        self.entry_aswer.configure(foreground="#000000")
        self.entry_aswer.configure(highlightbackground="#d9d9d9")
        self.entry_aswer.configure(highlightcolor="black")
        self.entry_aswer.configure(insertbackground="black")
        self.entry_aswer.configure(selectbackground="#c4c4c4")
        self.entry_aswer.configure(selectforeground="black")
        self.entry_aswer.configure(textvariable=register_support.entity_answer)

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.025, rely=0.619, height=21, width=74)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Answer''')

        self.lable_answer_error = tk.Label(top)
        self.lable_answer_error.place(relx=0.198, rely=0.687, height=21
                , width=274)
        self.lable_answer_error.configure(activebackground="#f9f9f9")
        self.lable_answer_error.configure(activeforeground="black")
        self.lable_answer_error.configure(background="#d9d9d9")
        self.lable_answer_error.configure(disabledforeground="#a3a3a3")
        self.lable_answer_error.configure(foreground="#ff1f1f")
        self.lable_answer_error.configure(highlightbackground="#d9d9d9")
        self.lable_answer_error.configure(highlightcolor="black")

        self.lable_question_error = tk.Label(top)
        self.lable_question_error.place(relx=0.223, rely=0.55, height=21
                , width=284)
        self.lable_question_error.configure(activebackground="#f9f9f9")
        self.lable_question_error.configure(activeforeground="black")
        self.lable_question_error.configure(anchor='nw')
        self.lable_question_error.configure(background="#d9d9d9")
        self.lable_question_error.configure(disabledforeground="#a3a3a3")
        self.lable_question_error.configure(foreground="#ff1f1f")
        self.lable_question_error.configure(highlightbackground="#d9d9d9")
        self.lable_question_error.configure(highlightcolor="black")

        self.lable_username_error = tk.Label(top)
        self.lable_username_error.place(relx=0.223, rely=0.206, height=21
                , width=284)
        self.lable_username_error.configure(activebackground="#f9f9f9")
        self.lable_username_error.configure(activeforeground="black")
        self.lable_username_error.configure(anchor='nw')
        self.lable_username_error.configure(background="#d9d9d9")
        self.lable_username_error.configure(disabledforeground="#a3a3a3")
        self.lable_username_error.configure(foreground="#ff1f1f")
        self.lable_username_error.configure(highlightbackground="#d9d9d9")
        self.lable_username_error.configure(highlightcolor="black")

        self.lable_password_error = tk.Label(top)
        self.lable_password_error.place(relx=0.223, rely=0.344, height=41
                , width=284)
        self.lable_password_error.configure(activebackground="#f9f9f9")
        self.lable_password_error.configure(activeforeground="black")
        self.lable_password_error.configure(anchor='nw')
        self.lable_password_error.configure(background="#d9d9d9")
        self.lable_password_error.configure(disabledforeground="#a3a3a3")
        self.lable_password_error.configure(foreground="#ff1f1f")
        self.lable_password_error.configure(highlightbackground="#d9d9d9")
        self.lable_password_error.configure(highlightcolor="black")
        self.lable_password_error.configure(width=284)

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="black")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(font="-family {Segoe UI} -size 9")
        Popupmenu1.configure(foreground="black")
        Popupmenu1.post(event.x_root, event.y_root)

    @staticmethod
    def popup2(event, *args, **kwargs):
        Popupmenu2 = tk.Menu(root, tearoff=0)
        Popupmenu2.configure(activebackground="#f9f9f9")
        Popupmenu2.configure(activeborderwidth="1")
        Popupmenu2.configure(activeforeground="black")
        Popupmenu2.configure(background="#d9d9d9")
        Popupmenu2.configure(borderwidth="1")
        Popupmenu2.configure(disabledforeground="#a3a3a3")
        Popupmenu2.configure(font="-family {Segoe UI} -size 9")
        Popupmenu2.configure(foreground="black")
        Popupmenu2.post(event.x_root, event.y_root)

    @staticmethod
    def popup3(event, *args, **kwargs):
        Popupmenu3 = tk.Menu(root, tearoff=0)
        Popupmenu3.configure(activebackground="#f9f9f9")
        Popupmenu3.configure(activeborderwidth="1")
        Popupmenu3.configure(activeforeground="black")
        Popupmenu3.configure(background="#d9d9d9")
        Popupmenu3.configure(borderwidth="1")
        Popupmenu3.configure(disabledforeground="#a3a3a3")
        Popupmenu3.configure(font="-family {Segoe UI} -size 9")
        Popupmenu3.configure(foreground="black")
        Popupmenu3.post(event.x_root, event.y_root)

    def run(self,p1):
            print('self.run')
            sys.stdout.flush()

if __name__ == '__main__':
    vp_start_gui()





