#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  Apr 12, 2019 12:16:05 PM +0300  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 453x356+499+309
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1684 1031
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TFrame -background #d9d9d9
    ttk::frame $top.tFr46 \
        -borderwidth 2 -relief groove -width 455 -height 355 
    vTcl:DefineAlias "$top.tFr46" "register_frame" vTcl:WidgetProc "Toplevel1" 1
    bind $top.tFr46 <Key-Return> {
        self.run
    }
    set site_3_0 $top.tFr46
    label $site_3_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 12} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Username 
    vTcl:DefineAlias "$site_3_0.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent49 \
        -background white -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 12} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable entity_username 
    vTcl:DefineAlias "$site_3_0.ent49" "entry_username" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 12} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Password 
    vTcl:DefineAlias "$site_3_0.lab50" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -activebackground {#f9f9f9} -activeforeground black -anchor nw \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#ff1f1f} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text { } 
    vTcl:DefineAlias "$site_3_0.lab51" "lable_username_error" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent52 \
        -background white -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 12} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable entitiy_password 
    vTcl:DefineAlias "$site_3_0.ent52" "entry_password" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab53 \
        -activebackground {#f9f9f9} -activeforeground black -anchor nw \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#ff1f1f} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text { } 
    vTcl:DefineAlias "$site_3_0.lab53" "lable_password_error" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi54 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledbackground {#f0f0f0} \
        -disabledforeground {#a3a3a3} -font {-family {Segoe UI} -size 12} \
        -foreground black -from 1.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable spinbox_question -to 100.0 -values {1 2 6 79 {}} 
    vTcl:DefineAlias "$site_3_0.spi54" "Spinbox_question" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 12} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Quiestion 
    vTcl:DefineAlias "$site_3_0.lab55" "Label3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent56 \
        -background white -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 10} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable entity_answer 
    vTcl:DefineAlias "$site_3_0.ent56" "entry_aswer" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black -anchor nw \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 12} -foreground {#ff1f1f} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text { } 
    vTcl:DefineAlias "$site_3_0.lab57" "lable_question_error" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 12} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Answer 
    vTcl:DefineAlias "$site_3_0.lab58" "Label4" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but59 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.run -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Register 
    vTcl:DefineAlias "$site_3_0.but59" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 12} -foreground {#ff1f1f} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text { } 
    vTcl:DefineAlias "$site_3_0.lab60" "lable_answer_error" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab48 \
        -in $site_3_0 -x 10 -y 20 -width 84 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent49 \
        -in $site_3_0 -x 100 -y 20 -width 255 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 10 -y 80 -width 74 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 100 -y 50 -width 295 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent52 \
        -in $site_3_0 -x 100 -y 80 -width 255 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 100 -y 110 -width 295 -height 60 -anchor nw \
        -bordermode ignore 
    place $site_3_0.spi54 \
        -in $site_3_0 -x 100 -y 170 -width 255 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 10 -y 170 -width 74 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent56 \
        -in $site_3_0 -x 100 -y 240 -width 255 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 100 -y 200 -width 295 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 20 -y 240 -width 74 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but59 \
        -in $site_3_0 -x 180 -y 300 -width 87 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 100 -y 270 -width 295 -height 30 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.tFr46
    frame $top.fra62 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 75 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.fra62" "loin_frame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra62
    label $site_3_0.lab63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 12} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Username 
    vTcl:DefineAlias "$site_3_0.lab63" "Label11" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent64 \
        -background white -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 12} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable entity_username 
    vTcl:DefineAlias "$site_3_0.ent64" "entry_username1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab65 \
        -activebackground {#f9f9f9} -activeforeground black -anchor nw \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#ff1f1f} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text { } 
    vTcl:DefineAlias "$site_3_0.lab65" "lable_username_error1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab66 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 12} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Password 
    vTcl:DefineAlias "$site_3_0.lab66" "Label21" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent67 \
        -background white -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 12} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable entitiy_password 
    vTcl:DefineAlias "$site_3_0.ent67" "entry_password1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab68 \
        -activebackground {#f9f9f9} -activeforeground black -anchor nw \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#ff1f1f} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text { } 
    vTcl:DefineAlias "$site_3_0.lab68" "lable_password_error1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but69 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.login \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text login 
    vTcl:DefineAlias "$site_3_0.but69" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but43 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command self.update('login') \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text register 
    vTcl:DefineAlias "$site_3_0.but43" "Button3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab63 \
        -in $site_3_0 -x 30 -y 30 -width 84 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent64 \
        -in $site_3_0 -x 120 -y 30 -width 255 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 110 -y 70 -width 295 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 30 -y 130 -width 74 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent67 \
        -in $site_3_0 -x 120 -y 130 -width 255 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 120 -y 160 -width 295 -height 60 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but69 \
        -in $site_3_0 -x 180 -y 250 -width 97 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but43 \
        -in $site_3_0 -x 310 -y 250 -width 67 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tFr46 \
        -in $top -x 0 -y 0 -width 455 -relwidth 0 -height 355 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra62 \
        -in $top -x 0 -y 0 -width 455 -relwidth 0 -height 355 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

