test_name: test API headers validation

stages:
  - name: .
    request:
      url: http://127.0.0.1:50007/passwords/steam
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.Iz3t2IXaJlAtfIokCw6aqEBVnBBGrizHXPzROhsyo1gKva0HPPQ0QKfUK5jnW2JO4fJ1t_9kVVPsKp1q14xuf17GecrupgwKOAVG9U5ccJ_cfCmjAgWPAUODxo6UY9O6uvmjNAoznoB8fY5JtWao8-UBn6ZAM0NmNQ4UU9cSwU3YbdIPJD8QipvK8hF_4OTNmjAfFVrE6zpuS3ALCDJ9Ube7gAHurk_6ngVdGThimm53ZrlWvtwkQGSBsIm2y6JreG0cYg6b7kKT-CtNESxb40Ph-wTjwPe6_xMprS-3CFu16oqnnE1tU7gnnRvufqzdx1f2zhBm49lltI-sxJJf_A.-Oxxd7i9vf5ozssgPTPkmA.ttrTJ9j4nHs49c_HLa_6gI6lFQ_oxEfGKXndzL3prEKpCI8FMt3QdpLd1EwjSoojA9XbRJwJQiMzieMXfdKpJbgKNf-EpKjA1soAWdS_OBPlS9oAAhgLb4XT_ymbOxP1COePGGHALQB25apn0k-ANt2qN676Fqm6Nul1XnGSyjngClSvmYSfh7c0FUemhQmlfU2AAwBPzK38d1nyytom7CbvEHuSQfdjJ29ItMoEvhU.OY7havfv43NvEook9wZ_Qw
    response:
      status_code: 200



---

test_name: test API url validation

stages:
  - name: forbidden url
    request:
      url: http://127.0.0.1:50007/client/forbidden
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.Iz3t2IXaJlAtfIokCw6aqEBVnBBGrizHXPzROhsyo1gKva0HPPQ0QKfUK5jnW2JO4fJ1t_9kVVPsKp1q14xuf17GecrupgwKOAVG9U5ccJ_cfCmjAgWPAUODxo6UY9O6uvmjNAoznoB8fY5JtWao8-UBn6ZAM0NmNQ4UU9cSwU3YbdIPJD8QipvK8hF_4OTNmjAfFVrE6zpuS3ALCDJ9Ube7gAHurk_6ngVdGThimm53ZrlWvtwkQGSBsIm2y6JreG0cYg6b7kKT-CtNESxb40Ph-wTjwPe6_xMprS-3CFu16oqnnE1tU7gnnRvufqzdx1f2zhBm49lltI-sxJJf_A.-Oxxd7i9vf5ozssgPTPkmA.ttrTJ9j4nHs49c_HLa_6gI6lFQ_oxEfGKXndzL3prEKpCI8FMt3QdpLd1EwjSoojA9XbRJwJQiMzieMXfdKpJbgKNf-EpKjA1soAWdS_OBPlS9oAAhgLb4XT_ymbOxP1COePGGHALQB25apn0k-ANt2qN676Fqm6Nul1XnGSyjngClSvmYSfh7c0FUemhQmlfU2AAwBPzK38d1nyytom7CbvEHuSQfdjJ29ItMoEvhU.OY7havfv43NvEook9wZ_Qw
    response:
      status_code: 404

---

test_name: test API HTTP verb validation

stages:
  - name: forbidden verb
    request:
      url: http://127.0.0.1:50007/passwords
      method: PATCH
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.Iz3t2IXaJlAtfIokCw6aqEBVnBBGrizHXPzROhsyo1gKva0HPPQ0QKfUK5jnW2JO4fJ1t_9kVVPsKp1q14xuf17GecrupgwKOAVG9U5ccJ_cfCmjAgWPAUODxo6UY9O6uvmjNAoznoB8fY5JtWao8-UBn6ZAM0NmNQ4UU9cSwU3YbdIPJD8QipvK8hF_4OTNmjAfFVrE6zpuS3ALCDJ9Ube7gAHurk_6ngVdGThimm53ZrlWvtwkQGSBsIm2y6JreG0cYg6b7kKT-CtNESxb40Ph-wTjwPe6_xMprS-3CFu16oqnnE1tU7gnnRvufqzdx1f2zhBm49lltI-sxJJf_A.-Oxxd7i9vf5ozssgPTPkmA.ttrTJ9j4nHs49c_HLa_6gI6lFQ_oxEfGKXndzL3prEKpCI8FMt3QdpLd1EwjSoojA9XbRJwJQiMzieMXfdKpJbgKNf-EpKjA1soAWdS_OBPlS9oAAhgLb4XT_ymbOxP1COePGGHALQB25apn0k-ANt2qN676Fqm6Nul1XnGSyjngClSvmYSfh7c0FUemhQmlfU2AAwBPzK38d1nyytom7CbvEHuSQfdjJ29ItMoEvhU.OY7havfv43NvEook9wZ_Qw
    response:
      status_code: 405
      headers:
        Access-Control-Request-Method: GET POST DELETE


  - name: alowed verb
    request:
      url: http://127.0.0.1:50007/passwords
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.Iz3t2IXaJlAtfIokCw6aqEBVnBBGrizHXPzROhsyo1gKva0HPPQ0QKfUK5jnW2JO4fJ1t_9kVVPsKp1q14xuf17GecrupgwKOAVG9U5ccJ_cfCmjAgWPAUODxo6UY9O6uvmjNAoznoB8fY5JtWao8-UBn6ZAM0NmNQ4UU9cSwU3YbdIPJD8QipvK8hF_4OTNmjAfFVrE6zpuS3ALCDJ9Ube7gAHurk_6ngVdGThimm53ZrlWvtwkQGSBsIm2y6JreG0cYg6b7kKT-CtNESxb40Ph-wTjwPe6_xMprS-3CFu16oqnnE1tU7gnnRvufqzdx1f2zhBm49lltI-sxJJf_A.-Oxxd7i9vf5ozssgPTPkmA.ttrTJ9j4nHs49c_HLa_6gI6lFQ_oxEfGKXndzL3prEKpCI8FMt3QdpLd1EwjSoojA9XbRJwJQiMzieMXfdKpJbgKNf-EpKjA1soAWdS_OBPlS9oAAhgLb4XT_ymbOxP1COePGGHALQB25apn0k-ANt2qN676Fqm6Nul1XnGSyjngClSvmYSfh7c0FUemhQmlfU2AAwBPzK38d1nyytom7CbvEHuSQfdjJ29ItMoEvhU.OY7havfv43NvEook9wZ_Qw


    response:
      status_code: 200

---
test_name: test JWT validation

stages:
  - name: forbidden header
    request:
      url: http://127.0.0.1:50007/passwords
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearrrrr eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.DeDvJLjwUCnv-q7WUY8TFLvDfZ0UnE4Gsv-MZOCaJMCfloO4HdQZiEeGnzWbMIeEvpFQQNSAKuEjL0zIHELavPcFC4kpt2NH0MnKTIr75sN0GW_WJwy9uOpMcWLxhViVm-o2zycZd-xrAvDO9w7M_6R7z_y4QhrA_5m5pxN1_WZyNlOlXu_GDkSF54I6jQDZxaia3onmeesxxys-88QXMD2vl5D9To5VnZBhIjvt2mUGitpvY6Q-GmYhVBLEI_2NOOOusZB2a13ZuP0iDMmk7H6gLtFRym26R6xDoWRsT6HzS8yeL8Pfp2qJ23QeLb4i4EMlVXCktQQfsT5aD1iLVA.NCCdUI7C_85wSTJiNNCbKQ.SW4N2bWkDhVnkdvjB9iNA5PUUo3lszcZRDqmr9EUXC5Mac_seHvVKv1tPO0On6wmG8fakgdgzKTEfaSTLVworKzJK8Wgv-Tzk_3fLZoueWH8NjUTaKHbgpJ-5TUBz5mgOv71x17_1fv-2YcW9ZhCLIifzvoOys5eKXIWytaDXqJ5BjZ-Spvdez_Z2bmG7llBzDNN7CLPuN4SdsZeCl7CyOKdNKGZDPKpeZaLYDby0qE.C6YkqvSn-VPXBwvcvkyAbQ
    response:
      status_code: 400
