test_name: test API headers validation

stages:
  - name: r

    request:
      url: http://127.0.0.1:50007/client/try
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.RhCVWJRz9tvKKy6bfj2qUhm4P9oFg5lgSev8qN2m67-36a10pVGJVba7YDk0PcptfAzjtGL_-ipAqPV5tTT3BrKwuznS_ArJkmpuAv9d6JwJZxSAQy5SNnJrAD54--Xh1K80Wk2V1Cq3y3PsM4NfXOEemG1V51i80l5stcw_l13GYchDR7C30jtk_VON0-6MSbZ3pWkHPGaJI9SIDHzM3cqmXli1hmRe1je696yoAAQBWAVxMwdYxSFYjPegNXmHB0PcitNz2BfzsjdPNrGYS0OMKtlZj5NCXMD4sm6_79pK554pakn5fbGJWO6-f3GOQHTiET8Rk7Se3VXmL4oMwg.V_I9Ql3d2aPXnM0xevx40g.4kqNguAo3hMQRO8_yCGPNPZf4Hfg0EOUSTX6N7DHSwTF_555YFQIk2TwTmHJsSACdrB0H9nqhsplA783Ls0QKuVIeZgV1Nx7BNmZ7ZfwA-XDGPHCcLtgzsmQllGid_dY8oFb9BiWU3638wWMc-mO8pbFlxM5YQmWYFIiuPFNy18m3gl3G4O8ldRUA2EZvbJe3di8SS79QfiiZ_RczIR0P-owhnUQWwT56RgfHVbW05g.OzA_nYxaoy-de0sTfjvblQ
    response:
      status_code: 200
---

test_name: test API url validation

stages:
  - name: forbidden url
    request:
      url: http://127.0.0.1:50007/client/try/forbidden
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.RhCVWJRz9tvKKy6bfj2qUhm4P9oFg5lgSev8qN2m67-36a10pVGJVba7YDk0PcptfAzjtGL_-ipAqPV5tTT3BrKwuznS_ArJkmpuAv9d6JwJZxSAQy5SNnJrAD54--Xh1K80Wk2V1Cq3y3PsM4NfXOEemG1V51i80l5stcw_l13GYchDR7C30jtk_VON0-6MSbZ3pWkHPGaJI9SIDHzM3cqmXli1hmRe1je696yoAAQBWAVxMwdYxSFYjPegNXmHB0PcitNz2BfzsjdPNrGYS0OMKtlZj5NCXMD4sm6_79pK554pakn5fbGJWO6-f3GOQHTiET8Rk7Se3VXmL4oMwg.V_I9Ql3d2aPXnM0xevx40g.4kqNguAo3hMQRO8_yCGPNPZf4Hfg0EOUSTX6N7DHSwTF_555YFQIk2TwTmHJsSACdrB0H9nqhsplA783Ls0QKuVIeZgV1Nx7BNmZ7ZfwA-XDGPHCcLtgzsmQllGid_dY8oFb9BiWU3638wWMc-mO8pbFlxM5YQmWYFIiuPFNy18m3gl3G4O8ldRUA2EZvbJe3di8SS79QfiiZ_RczIR0P-owhnUQWwT56RgfHVbW05g.OzA_nYxaoy-de0sTfjvblQ
    response:
      status_code: 404
  - name: alowed url
    request:
      url: http://127.0.0.1:50007/client/try
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.RhCVWJRz9tvKKy6bfj2qUhm4P9oFg5lgSev8qN2m67-36a10pVGJVba7YDk0PcptfAzjtGL_-ipAqPV5tTT3BrKwuznS_ArJkmpuAv9d6JwJZxSAQy5SNnJrAD54--Xh1K80Wk2V1Cq3y3PsM4NfXOEemG1V51i80l5stcw_l13GYchDR7C30jtk_VON0-6MSbZ3pWkHPGaJI9SIDHzM3cqmXli1hmRe1je696yoAAQBWAVxMwdYxSFYjPegNXmHB0PcitNz2BfzsjdPNrGYS0OMKtlZj5NCXMD4sm6_79pK554pakn5fbGJWO6-f3GOQHTiET8Rk7Se3VXmL4oMwg.V_I9Ql3d2aPXnM0xevx40g.4kqNguAo3hMQRO8_yCGPNPZf4Hfg0EOUSTX6N7DHSwTF_555YFQIk2TwTmHJsSACdrB0H9nqhsplA783Ls0QKuVIeZgV1Nx7BNmZ7ZfwA-XDGPHCcLtgzsmQllGid_dY8oFb9BiWU3638wWMc-mO8pbFlxM5YQmWYFIiuPFNy18m3gl3G4O8ldRUA2EZvbJe3di8SS79QfiiZ_RczIR0P-owhnUQWwT56RgfHVbW05g.OzA_nYxaoy-de0sTfjvblQ
    response:
      status_code: 200

---

test_name: test API HTTP verb validation

stages:
  - name: forbidden verb
    request:
      url: http://127.0.0.1:50007/client/try
      method: DELETE
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.RhCVWJRz9tvKKy6bfj2qUhm4P9oFg5lgSev8qN2m67-36a10pVGJVba7YDk0PcptfAzjtGL_-ipAqPV5tTT3BrKwuznS_ArJkmpuAv9d6JwJZxSAQy5SNnJrAD54--Xh1K80Wk2V1Cq3y3PsM4NfXOEemG1V51i80l5stcw_l13GYchDR7C30jtk_VON0-6MSbZ3pWkHPGaJI9SIDHzM3cqmXli1hmRe1je696yoAAQBWAVxMwdYxSFYjPegNXmHB0PcitNz2BfzsjdPNrGYS0OMKtlZj5NCXMD4sm6_79pK554pakn5fbGJWO6-f3GOQHTiET8Rk7Se3VXmL4oMwg.V_I9Ql3d2aPXnM0xevx40g.4kqNguAo3hMQRO8_yCGPNPZf4Hfg0EOUSTX6N7DHSwTF_555YFQIk2TwTmHJsSACdrB0H9nqhsplA783Ls0QKuVIeZgV1Nx7BNmZ7ZfwA-XDGPHCcLtgzsmQllGid_dY8oFb9BiWU3638wWMc-mO8pbFlxM5YQmWYFIiuPFNy18m3gl3G4O8ldRUA2EZvbJe3di8SS79QfiiZ_RczIR0P-owhnUQWwT56RgfHVbW05g.OzA_nYxaoy-de0sTfjvblQ
    response:
      status_code: 405
      headers:
        Access-Control-Request-Method: GET POST
  - name: alowed verb
    request:
      url: http://127.0.0.1:50007/client/try
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.RhCVWJRz9tvKKy6bfj2qUhm4P9oFg5lgSev8qN2m67-36a10pVGJVba7YDk0PcptfAzjtGL_-ipAqPV5tTT3BrKwuznS_ArJkmpuAv9d6JwJZxSAQy5SNnJrAD54--Xh1K80Wk2V1Cq3y3PsM4NfXOEemG1V51i80l5stcw_l13GYchDR7C30jtk_VON0-6MSbZ3pWkHPGaJI9SIDHzM3cqmXli1hmRe1je696yoAAQBWAVxMwdYxSFYjPegNXmHB0PcitNz2BfzsjdPNrGYS0OMKtlZj5NCXMD4sm6_79pK554pakn5fbGJWO6-f3GOQHTiET8Rk7Se3VXmL4oMwg.V_I9Ql3d2aPXnM0xevx40g.4kqNguAo3hMQRO8_yCGPNPZf4Hfg0EOUSTX6N7DHSwTF_555YFQIk2TwTmHJsSACdrB0H9nqhsplA783Ls0QKuVIeZgV1Nx7BNmZ7ZfwA-XDGPHCcLtgzsmQllGid_dY8oFb9BiWU3638wWMc-mO8pbFlxM5YQmWYFIiuPFNy18m3gl3G4O8ldRUA2EZvbJe3di8SS79QfiiZ_RczIR0P-owhnUQWwT56RgfHVbW05g.OzA_nYxaoy-de0sTfjvblQ
    response:
      status_code: 200

