test_name: test API headers validation

stages:
  - name: r

    request:
      url: http://127.0.0.1:50007/client/try
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.MR7QSc9M_8jVgSFEQzYe33_mabbSHcb5e-R-GjTIBDEsLzXd91Lkziv0pr4rIdUPWl1PyNKr46P9Ik1-errD4kRX3v-EpSbtRF1t1707_bEjVo5NAnSNg3lmvmtH9pc0OxUByPV0CsV2NHQEWKKtTWTFI3IpGlgoAxiEpSyBMhI3Xj8bUSbV9VikW_x93cdGsRo5UvG3KMSzMmCKnxRCfXZN5BLgy-RnYcJEo9LpumRyKlnaMC-rJwDghbqy7ke3jkbhll3VpCGV8WmgzAwkrmMUu5wWoQxKYQeeJbQ2z_F_hHjxmpg7hzLuGLv2xiEA1OJ6kybAaJ9M2ntm5vYOrw.B4-6JItGniGYlKOxQhPvkw.U0XBr-4IkUM6UPkyb1OKe5zT8GUTbpmCpuezG-8Lc9pWTri5CI6-UoYTiSxAdYx1LnDbiDnLmKwSfG5fXAJTbiLMW8KPHDk3-mG43ld7L3YTR_X9rbCgdhPC6eiycFPC7UA6WTaIJmIVtfnjF4ABZ42zZFRhFhdUKXhsdLN-diFYKd93b3X42YZDwXMVdjtsaYUiNofFX71FC-STVVCUxH05LJKa4Rho2WWPIbziHpM.JgivWbq91nBmPiEWl0-dow
    response:
      status_code: 200
---

test_name: test API url validation

stages:
  - name: forbidden url
    request:
      url: http://127.0.0.1:50007/client/try/forbidden
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.MR7QSc9M_8jVgSFEQzYe33_mabbSHcb5e-R-GjTIBDEsLzXd91Lkziv0pr4rIdUPWl1PyNKr46P9Ik1-errD4kRX3v-EpSbtRF1t1707_bEjVo5NAnSNg3lmvmtH9pc0OxUByPV0CsV2NHQEWKKtTWTFI3IpGlgoAxiEpSyBMhI3Xj8bUSbV9VikW_x93cdGsRo5UvG3KMSzMmCKnxRCfXZN5BLgy-RnYcJEo9LpumRyKlnaMC-rJwDghbqy7ke3jkbhll3VpCGV8WmgzAwkrmMUu5wWoQxKYQeeJbQ2z_F_hHjxmpg7hzLuGLv2xiEA1OJ6kybAaJ9M2ntm5vYOrw.B4-6JItGniGYlKOxQhPvkw.U0XBr-4IkUM6UPkyb1OKe5zT8GUTbpmCpuezG-8Lc9pWTri5CI6-UoYTiSxAdYx1LnDbiDnLmKwSfG5fXAJTbiLMW8KPHDk3-mG43ld7L3YTR_X9rbCgdhPC6eiycFPC7UA6WTaIJmIVtfnjF4ABZ42zZFRhFhdUKXhsdLN-diFYKd93b3X42YZDwXMVdjtsaYUiNofFX71FC-STVVCUxH05LJKa4Rho2WWPIbziHpM.JgivWbq91nBmPiEWl0-dow
    response:
      status_code: 404
  - name: alowed url
    request:
      url: http://127.0.0.1:50007/client/try
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.MR7QSc9M_8jVgSFEQzYe33_mabbSHcb5e-R-GjTIBDEsLzXd91Lkziv0pr4rIdUPWl1PyNKr46P9Ik1-errD4kRX3v-EpSbtRF1t1707_bEjVo5NAnSNg3lmvmtH9pc0OxUByPV0CsV2NHQEWKKtTWTFI3IpGlgoAxiEpSyBMhI3Xj8bUSbV9VikW_x93cdGsRo5UvG3KMSzMmCKnxRCfXZN5BLgy-RnYcJEo9LpumRyKlnaMC-rJwDghbqy7ke3jkbhll3VpCGV8WmgzAwkrmMUu5wWoQxKYQeeJbQ2z_F_hHjxmpg7hzLuGLv2xiEA1OJ6kybAaJ9M2ntm5vYOrw.B4-6JItGniGYlKOxQhPvkw.U0XBr-4IkUM6UPkyb1OKe5zT8GUTbpmCpuezG-8Lc9pWTri5CI6-UoYTiSxAdYx1LnDbiDnLmKwSfG5fXAJTbiLMW8KPHDk3-mG43ld7L3YTR_X9rbCgdhPC6eiycFPC7UA6WTaIJmIVtfnjF4ABZ42zZFRhFhdUKXhsdLN-diFYKd93b3X42YZDwXMVdjtsaYUiNofFX71FC-STVVCUxH05LJKa4Rho2WWPIbziHpM.JgivWbq91nBmPiEWl0-dow
    response:
      status_code: 200


---

test_name: test API url validation

stages:
  - name: forbidden url
    request:
      url: http://127.0.0.1:50007/client/try/forbidden
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.MR7QSc9M_8jVgSFEQzYe33_mabbSHcb5e-R-GjTIBDEsLzXd91Lkziv0pr4rIdUPWl1PyNKr46P9Ik1-errD4kRX3v-EpSbtRF1t1707_bEjVo5NAnSNg3lmvmtH9pc0OxUByPV0CsV2NHQEWKKtTWTFI3IpGlgoAxiEpSyBMhI3Xj8bUSbV9VikW_x93cdGsRo5UvG3KMSzMmCKnxRCfXZN5BLgy-RnYcJEo9LpumRyKlnaMC-rJwDghbqy7ke3jkbhll3VpCGV8WmgzAwkrmMUu5wWoQxKYQeeJbQ2z_F_hHjxmpg7hzLuGLv2xiEA1OJ6kybAaJ9M2ntm5vYOrw.B4-6JItGniGYlKOxQhPvkw.U0XBr-4IkUM6UPkyb1OKe5zT8GUTbpmCpuezG-8Lc9pWTri5CI6-UoYTiSxAdYx1LnDbiDnLmKwSfG5fXAJTbiLMW8KPHDk3-mG43ld7L3YTR_X9rbCgdhPC6eiycFPC7UA6WTaIJmIVtfnjF4ABZ42zZFRhFhdUKXhsdLN-diFYKd93b3X42YZDwXMVdjtsaYUiNofFX71FC-STVVCUxH05LJKa4Rho2WWPIbziHpM.JgivWbq91nBmPiEWl0-dow
    response:
      status_code: 404
  - name: alowed url
    request:
      url: http://127.0.0.1:50007/client/try
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.MR7QSc9M_8jVgSFEQzYe33_mabbSHcb5e-R-GjTIBDEsLzXd91Lkziv0pr4rIdUPWl1PyNKr46P9Ik1-errD4kRX3v-EpSbtRF1t1707_bEjVo5NAnSNg3lmvmtH9pc0OxUByPV0CsV2NHQEWKKtTWTFI3IpGlgoAxiEpSyBMhI3Xj8bUSbV9VikW_x93cdGsRo5UvG3KMSzMmCKnxRCfXZN5BLgy-RnYcJEo9LpumRyKlnaMC-rJwDghbqy7ke3jkbhll3VpCGV8WmgzAwkrmMUu5wWoQxKYQeeJbQ2z_F_hHjxmpg7hzLuGLv2xiEA1OJ6kybAaJ9M2ntm5vYOrw.B4-6JItGniGYlKOxQhPvkw.U0XBr-4IkUM6UPkyb1OKe5zT8GUTbpmCpuezG-8Lc9pWTri5CI6-UoYTiSxAdYx1LnDbiDnLmKwSfG5fXAJTbiLMW8KPHDk3-mG43ld7L3YTR_X9rbCgdhPC6eiycFPC7UA6WTaIJmIVtfnjF4ABZ42zZFRhFhdUKXhsdLN-diFYKd93b3X42YZDwXMVdjtsaYUiNofFX71FC-STVVCUxH05LJKa4Rho2WWPIbziHpM.JgivWbq91nBmPiEWl0-dow
    response:
      status_code: 200

---

test_name: test API HTTP verb validation

stages:
  - name: forbidden verb
    request:
      url: http://127.0.0.1:50007/client/try
      method: DELETE
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.MR7QSc9M_8jVgSFEQzYe33_mabbSHcb5e-R-GjTIBDEsLzXd91Lkziv0pr4rIdUPWl1PyNKr46P9Ik1-errD4kRX3v-EpSbtRF1t1707_bEjVo5NAnSNg3lmvmtH9pc0OxUByPV0CsV2NHQEWKKtTWTFI3IpGlgoAxiEpSyBMhI3Xj8bUSbV9VikW_x93cdGsRo5UvG3KMSzMmCKnxRCfXZN5BLgy-RnYcJEo9LpumRyKlnaMC-rJwDghbqy7ke3jkbhll3VpCGV8WmgzAwkrmMUu5wWoQxKYQeeJbQ2z_F_hHjxmpg7hzLuGLv2xiEA1OJ6kybAaJ9M2ntm5vYOrw.B4-6JItGniGYlKOxQhPvkw.U0XBr-4IkUM6UPkyb1OKe5zT8GUTbpmCpuezG-8Lc9pWTri5CI6-UoYTiSxAdYx1LnDbiDnLmKwSfG5fXAJTbiLMW8KPHDk3-mG43ld7L3YTR_X9rbCgdhPC6eiycFPC7UA6WTaIJmIVtfnjF4ABZ42zZFRhFhdUKXhsdLN-diFYKd93b3X42YZDwXMVdjtsaYUiNofFX71FC-STVVCUxH05LJKa4Rho2WWPIbziHpM.JgivWbq91nBmPiEWl0-dow
    response:
      status_code: 405
      headers:
        Access-Control-Request-Method: GET POST
  - name: alowed verb
    request:
      url: http://127.0.0.1:50007/client/try
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.MR7QSc9M_8jVgSFEQzYe33_mabbSHcb5e-R-GjTIBDEsLzXd91Lkziv0pr4rIdUPWl1PyNKr46P9Ik1-errD4kRX3v-EpSbtRF1t1707_bEjVo5NAnSNg3lmvmtH9pc0OxUByPV0CsV2NHQEWKKtTWTFI3IpGlgoAxiEpSyBMhI3Xj8bUSbV9VikW_x93cdGsRo5UvG3KMSzMmCKnxRCfXZN5BLgy-RnYcJEo9LpumRyKlnaMC-rJwDghbqy7ke3jkbhll3VpCGV8WmgzAwkrmMUu5wWoQxKYQeeJbQ2z_F_hHjxmpg7hzLuGLv2xiEA1OJ6kybAaJ9M2ntm5vYOrw.B4-6JItGniGYlKOxQhPvkw.U0XBr-4IkUM6UPkyb1OKe5zT8GUTbpmCpuezG-8Lc9pWTri5CI6-UoYTiSxAdYx1LnDbiDnLmKwSfG5fXAJTbiLMW8KPHDk3-mG43ld7L3YTR_X9rbCgdhPC6eiycFPC7UA6WTaIJmIVtfnjF4ABZ42zZFRhFhdUKXhsdLN-diFYKd93b3X42YZDwXMVdjtsaYUiNofFX71FC-STVVCUxH05LJKa4Rho2WWPIbziHpM.JgivWbq91nBmPiEWl0-dow
    response:
      status_code: 200

