test_name: test API headers validation

stages:
  - name: r

    request:
      url: http://127.0.0.1:50007/client/try
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.Qd9_ABbm9S0U1XIfyVxvn12c8CU2bwfnvKqWviCht7eFRIeSCPdiNrapEwhRbLCS-2Cmumuhu0xcogLFDMWK1qT3OPRtGAFaB-uUPQ9hl83jrWPhSaJV2pzjKqbVhGFiZgv4EAdUSLj1tDqo7AOtWKvydtGvmzrylxPrt2SUkhssa10Rl7q5fNVzxUgqlPpqsqbrewkNG6nhvEVdUHyj3xNMxa8gG4D17ActstuleYOwdSGQ1Jl3aelrggffbpbem5IZEGHi8gIRaiJOk-0iaVzrbq2wuQb7x_7ZBCWJ9K5px2qOwzUGMRWpG8ivEuCMR_Igy8tRejDaEBN4UBnyeg.S-F8JevZugW9T93DGs7Ygg.trc26MJuYZSfoAAQguW7OsUJkq1sfwcyt5T4KGoOInNtWxXt0HexF3Grj80feyH6W4pj53s1cEP17JEqgpdqxZbDSOUXXzCxPNQkPTm1h91xg9CMCeKjUUUoe4zTYqv_-nnitFjb5Sh951w7yz4dRKfDwNxEa2t-mjD30EFv60DVTlAFn-mdLVm7cwSRHSet5yrs2tpaT8QVQyXRNtgPfzm8R7moBYoNT8DU5X3COUE.UDLOha0KbqoBxf8SF6cuhw
    response:
      status_code: 200
---

test_name: test API url validation

stages:
  - name: forbidden url
    request:
      url: http://127.0.0.1:50007/client/try/forbidden
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.Qd9_ABbm9S0U1XIfyVxvn12c8CU2bwfnvKqWviCht7eFRIeSCPdiNrapEwhRbLCS-2Cmumuhu0xcogLFDMWK1qT3OPRtGAFaB-uUPQ9hl83jrWPhSaJV2pzjKqbVhGFiZgv4EAdUSLj1tDqo7AOtWKvydtGvmzrylxPrt2SUkhssa10Rl7q5fNVzxUgqlPpqsqbrewkNG6nhvEVdUHyj3xNMxa8gG4D17ActstuleYOwdSGQ1Jl3aelrggffbpbem5IZEGHi8gIRaiJOk-0iaVzrbq2wuQb7x_7ZBCWJ9K5px2qOwzUGMRWpG8ivEuCMR_Igy8tRejDaEBN4UBnyeg.S-F8JevZugW9T93DGs7Ygg.trc26MJuYZSfoAAQguW7OsUJkq1sfwcyt5T4KGoOInNtWxXt0HexF3Grj80feyH6W4pj53s1cEP17JEqgpdqxZbDSOUXXzCxPNQkPTm1h91xg9CMCeKjUUUoe4zTYqv_-nnitFjb5Sh951w7yz4dRKfDwNxEa2t-mjD30EFv60DVTlAFn-mdLVm7cwSRHSet5yrs2tpaT8QVQyXRNtgPfzm8R7moBYoNT8DU5X3COUE.UDLOha0KbqoBxf8SF6cuhw
    response:
      status_code: 404
  - name: alowed url
    request:
      url: http://127.0.0.1:50007/client/try
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.Qd9_ABbm9S0U1XIfyVxvn12c8CU2bwfnvKqWviCht7eFRIeSCPdiNrapEwhRbLCS-2Cmumuhu0xcogLFDMWK1qT3OPRtGAFaB-uUPQ9hl83jrWPhSaJV2pzjKqbVhGFiZgv4EAdUSLj1tDqo7AOtWKvydtGvmzrylxPrt2SUkhssa10Rl7q5fNVzxUgqlPpqsqbrewkNG6nhvEVdUHyj3xNMxa8gG4D17ActstuleYOwdSGQ1Jl3aelrggffbpbem5IZEGHi8gIRaiJOk-0iaVzrbq2wuQb7x_7ZBCWJ9K5px2qOwzUGMRWpG8ivEuCMR_Igy8tRejDaEBN4UBnyeg.S-F8JevZugW9T93DGs7Ygg.trc26MJuYZSfoAAQguW7OsUJkq1sfwcyt5T4KGoOInNtWxXt0HexF3Grj80feyH6W4pj53s1cEP17JEqgpdqxZbDSOUXXzCxPNQkPTm1h91xg9CMCeKjUUUoe4zTYqv_-nnitFjb5Sh951w7yz4dRKfDwNxEa2t-mjD30EFv60DVTlAFn-mdLVm7cwSRHSet5yrs2tpaT8QVQyXRNtgPfzm8R7moBYoNT8DU5X3COUE.UDLOha0KbqoBxf8SF6cuhw
    response:
      status_code: 200


---

test_name: test API url validation

stages:
  - name: forbidden url
    request:
      url: http://127.0.0.1:50007/client/try/forbidden
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.Qd9_ABbm9S0U1XIfyVxvn12c8CU2bwfnvKqWviCht7eFRIeSCPdiNrapEwhRbLCS-2Cmumuhu0xcogLFDMWK1qT3OPRtGAFaB-uUPQ9hl83jrWPhSaJV2pzjKqbVhGFiZgv4EAdUSLj1tDqo7AOtWKvydtGvmzrylxPrt2SUkhssa10Rl7q5fNVzxUgqlPpqsqbrewkNG6nhvEVdUHyj3xNMxa8gG4D17ActstuleYOwdSGQ1Jl3aelrggffbpbem5IZEGHi8gIRaiJOk-0iaVzrbq2wuQb7x_7ZBCWJ9K5px2qOwzUGMRWpG8ivEuCMR_Igy8tRejDaEBN4UBnyeg.S-F8JevZugW9T93DGs7Ygg.trc26MJuYZSfoAAQguW7OsUJkq1sfwcyt5T4KGoOInNtWxXt0HexF3Grj80feyH6W4pj53s1cEP17JEqgpdqxZbDSOUXXzCxPNQkPTm1h91xg9CMCeKjUUUoe4zTYqv_-nnitFjb5Sh951w7yz4dRKfDwNxEa2t-mjD30EFv60DVTlAFn-mdLVm7cwSRHSet5yrs2tpaT8QVQyXRNtgPfzm8R7moBYoNT8DU5X3COUE.UDLOha0KbqoBxf8SF6cuhw
    response:
      status_code: 404
  - name: alowed url
    request:
      url: http://127.0.0.1:50007/client/try
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.Qd9_ABbm9S0U1XIfyVxvn12c8CU2bwfnvKqWviCht7eFRIeSCPdiNrapEwhRbLCS-2Cmumuhu0xcogLFDMWK1qT3OPRtGAFaB-uUPQ9hl83jrWPhSaJV2pzjKqbVhGFiZgv4EAdUSLj1tDqo7AOtWKvydtGvmzrylxPrt2SUkhssa10Rl7q5fNVzxUgqlPpqsqbrewkNG6nhvEVdUHyj3xNMxa8gG4D17ActstuleYOwdSGQ1Jl3aelrggffbpbem5IZEGHi8gIRaiJOk-0iaVzrbq2wuQb7x_7ZBCWJ9K5px2qOwzUGMRWpG8ivEuCMR_Igy8tRejDaEBN4UBnyeg.S-F8JevZugW9T93DGs7Ygg.trc26MJuYZSfoAAQguW7OsUJkq1sfwcyt5T4KGoOInNtWxXt0HexF3Grj80feyH6W4pj53s1cEP17JEqgpdqxZbDSOUXXzCxPNQkPTm1h91xg9CMCeKjUUUoe4zTYqv_-nnitFjb5Sh951w7yz4dRKfDwNxEa2t-mjD30EFv60DVTlAFn-mdLVm7cwSRHSet5yrs2tpaT8QVQyXRNtgPfzm8R7moBYoNT8DU5X3COUE.UDLOha0KbqoBxf8SF6cuhw
    response:
      status_code: 200

---

test_name: test API HTTP verb validation

stages:
  - name: forbidden verb
    request:
      url: http://127.0.0.1:50007/client/try
      method: DELETE
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.Qd9_ABbm9S0U1XIfyVxvn12c8CU2bwfnvKqWviCht7eFRIeSCPdiNrapEwhRbLCS-2Cmumuhu0xcogLFDMWK1qT3OPRtGAFaB-uUPQ9hl83jrWPhSaJV2pzjKqbVhGFiZgv4EAdUSLj1tDqo7AOtWKvydtGvmzrylxPrt2SUkhssa10Rl7q5fNVzxUgqlPpqsqbrewkNG6nhvEVdUHyj3xNMxa8gG4D17ActstuleYOwdSGQ1Jl3aelrggffbpbem5IZEGHi8gIRaiJOk-0iaVzrbq2wuQb7x_7ZBCWJ9K5px2qOwzUGMRWpG8ivEuCMR_Igy8tRejDaEBN4UBnyeg.S-F8JevZugW9T93DGs7Ygg.trc26MJuYZSfoAAQguW7OsUJkq1sfwcyt5T4KGoOInNtWxXt0HexF3Grj80feyH6W4pj53s1cEP17JEqgpdqxZbDSOUXXzCxPNQkPTm1h91xg9CMCeKjUUUoe4zTYqv_-nnitFjb5Sh951w7yz4dRKfDwNxEa2t-mjD30EFv60DVTlAFn-mdLVm7cwSRHSet5yrs2tpaT8QVQyXRNtgPfzm8R7moBYoNT8DU5X3COUE.UDLOha0KbqoBxf8SF6cuhw
    response:
      status_code: 405
      headers:
        Access-Control-Request-Method: GET POST
  - name: alowed verb
    request:
      url: http://127.0.0.1:50007/client/try
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ0eXAiOiJKV0UifQ.Qd9_ABbm9S0U1XIfyVxvn12c8CU2bwfnvKqWviCht7eFRIeSCPdiNrapEwhRbLCS-2Cmumuhu0xcogLFDMWK1qT3OPRtGAFaB-uUPQ9hl83jrWPhSaJV2pzjKqbVhGFiZgv4EAdUSLj1tDqo7AOtWKvydtGvmzrylxPrt2SUkhssa10Rl7q5fNVzxUgqlPpqsqbrewkNG6nhvEVdUHyj3xNMxa8gG4D17ActstuleYOwdSGQ1Jl3aelrggffbpbem5IZEGHi8gIRaiJOk-0iaVzrbq2wuQb7x_7ZBCWJ9K5px2qOwzUGMRWpG8ivEuCMR_Igy8tRejDaEBN4UBnyeg.S-F8JevZugW9T93DGs7Ygg.trc26MJuYZSfoAAQguW7OsUJkq1sfwcyt5T4KGoOInNtWxXt0HexF3Grj80feyH6W4pj53s1cEP17JEqgpdqxZbDSOUXXzCxPNQkPTm1h91xg9CMCeKjUUUoe4zTYqv_-nnitFjb5Sh951w7yz4dRKfDwNxEa2t-mjD30EFv60DVTlAFn-mdLVm7cwSRHSet5yrs2tpaT8QVQyXRNtgPfzm8R7moBYoNT8DU5X3COUE.UDLOha0KbqoBxf8SF6cuhw
    response:
      status_code: 200

