test_name: test API headers validation

stages:
  - name: r
    request:
      url: http://127.0.0.1:50007/client/try
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer aa.bb.cc
    response:
      status_code: 200

---

test_name: test API url validation

stages:
  - name: forbidden url
    request:
      url: http://127.0.0.1:50007/client/try/forbidden
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer aa.bb.cc
    response:
      status_code: 404
  - name: alowed url
    request:
      url: http://127.0.0.1:50007/client/try
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer aa.bb.cc
    response:
      status_code: 200

---

test_name: test API HTTP verb validation

stages:
  - name: forbidden verb
    request:
      url: http://127.0.0.1:50007/client/try
      method: DELETE
      headers:
        Content-Type: application/json
        Authorization: Bearer aa.bb.cc
    response:
      status_code: 405
      headers:
        Access-Control-Request-Method: GET POST
  - name: alowed verb
    request:
      url: http://127.0.0.1:50007/client/try
      method: GET
      headers:
        Content-Type: application/json
        Authorization: Bearer aa.bb.cc
    response:
      status_code: 200

